### ISSUE TITLE
Host and Port Environment variable not passing through

### ISSUE THREAD

**Issue by T-burger** [OneMoreByte/hydroxide-container#2]
Hi,
Not sure if I am missing something simple but I can't change any of the Host IP's or ports from the Hydroxide defaults.

I have been using the following docker-compose:
```
version: '3'

services:
  hydroxide:
    container_name: hydroxide
    image: jsckh/hydroxide
    ports:
      - 1143:1143
      - 1025:1025
    volumes:
      - $HOME/.config/hydroxide:/home/hydroxide/.config/hydroxide:rw
    environment:
      - HYDROXIDE_SMTP_HOST=0.0.0.0
      - HYDROXIDE_SMTP_PORT=1025
      - HYDROXIDE_IMAP_HOST="0.0.0.0"
      - HYDROXIDE_IMAP_PORT='1143'
      - HYDROXIDE_NO_SMTP=false
      - HYDROXIDE_NO_IMAP=false
      - HYDROXIDE_NO_CARDDAV=true

````

I have tried removing all environment variables, which should change the IP to 0.0.0.0.

But I always get the same respose, when I run docker-compose up, :

```` 
Starting hydroxide ... done
Attaching to hydroxide
hydroxide    | 2022/06/28 11:18:42 SMTP server listening on 127.0.0.1:1025
hydroxide    | 2022/06/28 11:18:42 IMAP server listening on 127.0.0.1:1143
````
From what I understand if the processes run on 127.0.0.1 they wont pass-thru properly to the host, I could be mistaken. However when I try to connect to the IMAP port from applications running on the host (just testing with mutt for now), the connection fails. If I run hydroxide manually on the host I can connect fine.

Any help would be great
thanks
